language: python

env:
  global:
  - USER="dedeswim"
  - EMAIL="deploy@travis-ci.org"
  - DEPLOYMENT_USER="traviscibot"
  - REPO="dedeswim.github.io"
  - FILES="./public/*"
  - GH_REPO="github.com/${USER}/${REPO}.git"

after_success:
  - MESSAGE=$('Commit with Travis CI')
  - git clone git://${GH_REPO}
  - cp -f ${FILES} ${REPO}
  - cd ${REPO}
  - ls
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${DEPLOYMENT_USER}
  - git add .
  - git commit -m ${MESSAGE}
  - git push "https://${GITHUB_TOKEN}@${GH_REPO}" master

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.41/hugo_0.41_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

script:
    - hugo -s ./