baseURL = "https://edoardodebenedetti.me"
languageCode = "en-us"
title = "edoardo_debenedetti"
tags = ["portfolio", "web design", "blog", "develpment"]
config = "config.toml"
theme = "coder"
canonifyURLS = true

[params] # theme parameters
    author = "edoardo_debenedetti" # author's name
    copyrightName = "Edoardo Debenedetti"
    pippo = ""
    footerEmail = "\u0065\u0064\u006f\u0061\u0072\u0064\u006f\u002e\u006d\u002e\u0064\u0065\u0062\u0065\u006e\u0065\u0064\u0065\u0074\u0074\u0069\u0040\u0067\u006d\u0061\u0069\u006c\u002e\u0063\u006f\u006d"
    info = "Computer Engineering B.Sc. student" # author's job title or info
    description = "Edoardo Debenedetti's personal website" # site description
    keywords = "blog,developer,personal,portfolio" # site keywords
    homeImagePath = "res/img/great-wall.jpg"
    sub = "(Yes, I like underscores)"
    color = "#01579b"
    
    # wether you want to hide copyright and credits in the footer
    hideCredits = true
    hideCopyright = false

    
# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/dedeswim/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/edoardo-debenedetti/"
[[params.social]]
    name = "Instagram"
    weight = 2
    url = "http://instagram.com/edoardo.debenedetti"

# Menu links
[[menu.main]]
     name = "Blog"
     weight = 1
     url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Pindery"
    weight = 2
    url = "https://aeeooto.github.io/pindery"