baseURL = "https://edoardodebenedetti.me"
languageCode = "en-us"
title = "edoardo_debenedetti"
tags = ["portfolio", "web design", "blog", "develpment"]
config = "config.toml"
theme = "coder"
canonifyURLS = true

[params] # theme parameters
    author = "edoardo_debenedetti" # author's name
    copyrightName = "Edoardo Debenedetti"
    info = "Computer Engineering student" # author's job title or info
    description = "Edoardo Debenedetti's personal website" # site description
    keywords = "blog,developer,personal,portfolio" # site keywords

    # wether you want to hide copyright and credits in the footer
    hideCredits = true
    hideCopyright = false
    
# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/dedeswim/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/edoardo_debe/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/edoardo-debenedetti/"

# Menu links
[[menu.main]]
     name = "Blog"
     weight = 1
     url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"